extends Resource
class_name ItemData

enum ITEM_TYPE {OTHER, EQUIPMENT, SPELLCARD, CONSUMABLE}
enum ITEM_SUB_TYPE {
	MISC, ONE_HANDED, TWO_HANDED, HAT, CLOTHING, GLOVES, SHOES,
	PROJECTILE, ATTACK_MODIFIER, MULTICAST,
	ON_FIRE_PROJECTILE_MODIFIER, ON_HIT_PROJECTILE_MODIFIER,
	PROPERTIES_PROJECTILE_MODIFIER, ADDITIVE_PROPERTIES_PROJECTILE_MODIFIER,
	BEHAVIOR_PROJECTILE_MODIFIER, SUMMON, MOD_PROJECTILE_MODIFIER}

static var EMPTY_ITEM_DATA = ItemData.new()

@export var name: String = ""
@export var description: String = ""
@export var texture: Texture
@export var type: ITEM_TYPE
@export var sub_type: ITEM_SUB_TYPE
@export var key : String
@export var dict_key: String

static func get_type(s : String) -> ITEM_TYPE:
	if s == "EQUIPMENT":
		return ITEM_TYPE.EQUIPMENT
	elif s == "SPELLCARD":
		return ITEM_TYPE.SPELLCARD
	elif s == "CONSUMABLE":
		return ITEM_TYPE.CONSUMABLE
	else:
		return ITEM_TYPE.OTHER

## might be overridden?
static func get_sub_type(s) -> ITEM_SUB_TYPE:
	if s == "ONE_HANDED":
		return ITEM_SUB_TYPE.ONE_HANDED
	elif s == "TWO_HANDED":
		return ITEM_SUB_TYPE.TWO_HANDED
	elif s == "HAT":
		return ITEM_SUB_TYPE.HAT
	elif s == "CLOTHING":
		return ITEM_SUB_TYPE.CLOTHING
	elif s == "GLOVES":
		return ITEM_SUB_TYPE.GLOVES
	elif s == "SHOES":
		return ITEM_SUB_TYPE.SHOES
	elif s == "PROJECTILE":
		return ITEM_SUB_TYPE.PROJECTILE
	elif s == "SUMMON":
		return ITEM_SUB_TYPE.SUMMON
	elif s == "ATTACK_MODIFIER":
		return ITEM_SUB_TYPE.ATTACK_MODIFIER
	elif s == "MOD_PROJECTILE_MODIFIER":
		return ITEM_SUB_TYPE.MOD_PROJECTILE_MODIFIER
	elif s == "ADDITIVE_PROPERTIES_PROJECTILE_MODIFIER":
		return ITEM_SUB_TYPE.ADDITIVE_PROPERTIES_PROJECTILE_MODIFIER
	elif s == "MULTICAST":
		return ITEM_SUB_TYPE.MULTICAST
	elif s == "ON_FIRE_PROJECTILE_MODIFIER":
		return ITEM_SUB_TYPE.ON_FIRE_PROJECTILE_MODIFIER
	elif s == "ON_HIT_PROJECTILE_MODIFIER":
		return ITEM_SUB_TYPE.ON_HIT_PROJECTILE_MODIFIER
	elif s == "PROPERTIES_PROJECTILE_MODIFIER":
		return ITEM_SUB_TYPE.PROPERTIES_PROJECTILE_MODIFIER
	elif s == "BEHAVIOR_PROJECTILE_MODIFIER":
		return ITEM_SUB_TYPE.BEHAVIOR_PROJECTILE_MODIFIER
	else:
		return ITEM_SUB_TYPE.MISC
